# Generated by Django 5.0.4 on 2024-04-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=150, verbose_name='Модель продукта')),
                ('market_launch_date', models.DateTimeField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название завода')),
                ('time_to_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.contacts', verbose_name='Контакты')),
                ('provider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers.factory', verbose_name='Поставщик')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealers.products', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'завод',
                'verbose_name_plural': 'заводы',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название розничной сети')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Задолженность')),
                ('time_to_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.contacts', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealers.products', verbose_name='Продукты')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealers.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('time_to_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Задолженность')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.contacts', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealers.products', verbose_name='Продукты')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealers.retailnetwork', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Предприниматель',
                'verbose_name_plural': 'Предприниматели',
            },
        ),
    ]
