# Generated by Django 5.0.4 on 2024-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_products_factory_retailnetwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='house_number',
            field=models.CharField(max_length=50, verbose_name='Номер дома'),
        ),
    ]
