# Generated by Django 5.0.4 on 2024-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_contacts_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Задолженность'),
        ),
    ]
