# Generated by Django 5.0.4 on 2024-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_remove_factory_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(related_name='factory_product', to='dealers.products', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='products',
            field=models.ManyToManyField(related_name='entrepreneur_product', to='dealers.products', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='products',
            field=models.ManyToManyField(related_name='network_product', to='dealers.products', verbose_name='Продукты'),
        ),
    ]
