# Generated by Django 5.0.4 on 2024-04-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0007_alter_factory_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_contact', to='dealers.contacts', verbose_name='Контакты'),
        ),
    ]
